export const BUSINESS_DEALS_REQUEST = "BUSINESS_DEALS_REQUEST";
export const BUSINESS_DEALS_REQUEST_SUCCESS = "BUSINESS_DEALS_REQUEST_SUCCESS";
export const BUSINESS_DEALS_REQUEST_FAILURE = "BUSINESS_DEALS_REQUEST_FAILURE";

export const BUSINESSES_REQUEST = "BUSINESSES_REQUEST";
export const BUSINESSES_REQUEST_SUCCESS = "BUSINESSES_REQUEST_SUCCESS";
export const BUSINESSES_REQUEST_FAILURE = "BUSINESSES_REQUEST_FAILURE";

export const GET_BUSINESS_BY_SERVICE_TYPE = "GET_BUSINESS_BY_SERVICE_TYPE";
