export const SET_SEARCH_FIELD_REQUEST = "SET_SEARCH_FIELD_REQUEST";

export const FILTER_BUSINESSES_SEARCH_REQUEST =
    "FILTER_BUSINESSES_SEARCH_REQUEST";
export const FILTER_BUSINESSES_SEARCH_REQUEST_SUCCESS =
    "FILTER_BUSINESSES_SEARCH_REQUEST_SUCCESS";
export const FILTER_BUSINESSES_SEARCH_REQUEST_FAILURE =
    "FILTER_BUSINESSES_SEARCH_REQUEST_FAILURE";
